import { PERMISSIONS, type Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<string, Set<Permission>> = {
  admin: new Set([
    PERMISSIONS.ADMIN_ACCESS,

    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,

    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_CANCEL,

    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_VERIFY,

    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,

    PERMISSIONS.PARTNERS_READ,
    PERMISSIONS.PARTNERS_APPROVE,

    PERMISSIONS.DISTRIBUTORS_READ,
    PERMISSIONS.DISTRIBUTORS_APPROVE,

    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_DELETE,

    PERMISSIONS.DIAGNOSTICS_VIEW,
  ]),

  superadmin: new Set(Object.values(PERMISSIONS)),
};