/**
 * Supabase database types.
 *
 * This file is regenerated by:
 *   pnpm supabase:types
 *
 * Until the first generation runs against the live Supabase project, this
 * placeholder allows the app to compile.
 */

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
