/**
 * Supabase database types.
 *
 * This file is regenerated by:
 *   npm run supabase:types
 *
 * Until that command runs against the live Supabase project, hand-written
 * shapes below cover the tables the app actually queries. The generator will
 * overwrite this file; do not rely on these definitions long-term.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [k: string]: Json | undefined }
  | Json[]

type Timestamptz = string
type UserRoleEnum = 'customer' | 'distributor' | 'admin' | 'superadmin'

export type Database = {
  public: {
    Tables: {
      categories: {
        Row: {
          id: number
          slug: string
          name: string
          parent_id: number | null
          position: number
          is_active: boolean
          created_at: Timestamptz
        }
        Insert: {
          id?: number
          slug: string
          name: string
          parent_id?: number | null
          position?: number
          is_active?: boolean
          created_at?: Timestamptz
        }
        Update: {
          id?: number
          slug?: string
          name?: string
          parent_id?: number | null
          position?: number
          is_active?: boolean
          created_at?: Timestamptz
        }
        Relationships: []
      }
      products: {
        Row: {
          id: number
          slug: string
          name: string
          description: string | null
          category_id: number | null
          is_active: boolean
          meta_title: string | null
          meta_description: string | null
          created_at: Timestamptz
          updated_at: Timestamptz
        }
        Insert: {
          id?: number
          slug: string
          name: string
          description?: string | null
          category_id?: number | null
          is_active?: boolean
          meta_title?: string | null
          meta_description?: string | null
          created_at?: Timestamptz
          updated_at?: Timestamptz
        }
        Update: {
          id?: number
          slug?: string
          name?: string
          description?: string | null
          category_id?: number | null
          is_active?: boolean
          meta_title?: string | null
          meta_description?: string | null
          created_at?: Timestamptz
          updated_at?: Timestamptz
        }
        Relationships: []
      }
      product_variants: {
        Row: {
          id: number
          product_id: number
          sku: string
          size_ml: number
          retail_price_minor: string
          distributor_price_minor: string
          weight_g: number | null
          inventory_qty: number
          is_active: boolean
          created_at: Timestamptz
        }
        Insert: {
          id?: number
          product_id: number
          sku: string
          size_ml: number
          retail_price_minor: string
          distributor_price_minor: string
          weight_g?: number | null
          inventory_qty?: number
          is_active?: boolean
          created_at?: Timestamptz
        }
        Update: {
          id?: number
          product_id?: number
          sku?: string
          size_ml?: number
          retail_price_minor?: string
          distributor_price_minor?: string
          weight_g?: number | null
          inventory_qty?: number
          is_active?: boolean
          created_at?: Timestamptz
        }
        Relationships: []
      }
      bundles: {
        Row: {
          id: number
          slug: string
          name: string
          description: string | null
          retail_price_minor: string
          distributor_price_minor: string
          currency: string
          is_starter_package: boolean
          starter_package_code: string | null
          is_active: boolean
          created_at: Timestamptz
        }
        Insert: {
          id?: number
          slug: string
          name: string
          description?: string | null
          retail_price_minor: string
          distributor_price_minor: string
          currency?: string
          is_starter_package?: boolean
          starter_package_code?: string | null
          is_active?: boolean
          created_at?: Timestamptz
        }
        Update: {
          id?: number
          slug?: string
          name?: string
          description?: string | null
          retail_price_minor?: string
          distributor_price_minor?: string
          currency?: string
          is_starter_package?: boolean
          starter_package_code?: string | null
          is_active?: boolean
          created_at?: Timestamptz
        }
        Relationships: []
      }
      bundle_items: {
        Row: {
          id: number
          bundle_id: number
          variant_id: number
          quantity: number
        }
        Insert: {
          id?: number
          bundle_id: number
          variant_id: number
          quantity: number
        }
        Update: {
          id?: number
          bundle_id?: number
          variant_id?: number
          quantity?: number
        }
        Relationships: []
      }
      product_images: {
        Row: {
          id: number
          product_id: number
          variant_id: number | null
          storage_prefix: string
          alt: string | null
          position: number
          width: number | null
          height: number | null
          is_primary: boolean
          created_at: Timestamptz
        }
        Insert: {
          id?: number
          product_id: number
          variant_id?: number | null
          storage_prefix: string
          alt?: string | null
          position?: number
          width?: number | null
          height?: number | null
          is_primary?: boolean
          created_at?: Timestamptz
        }
        Update: {
          id?: number
          product_id?: number
          variant_id?: number | null
          storage_prefix?: string
          alt?: string | null
          position?: number
          width?: number | null
          height?: number | null
          is_primary?: boolean
          created_at?: Timestamptz
        }
        Relationships: []
      }
      bundle_images: {
        Row: {
          id: number
          bundle_id: number
          storage_prefix: string
          alt: string | null
          position: number
          width: number | null
          height: number | null
          is_primary: boolean
          created_at: Timestamptz
        }
        Insert: {
          id?: number
          bundle_id: number
          storage_prefix: string
          alt?: string | null
          position?: number
          width?: number | null
          height?: number | null
          is_primary?: boolean
          created_at?: Timestamptz
        }
        Update: {
          id?: number
          bundle_id?: number
          storage_prefix?: string
          alt?: string | null
          position?: number
          width?: number | null
          height?: number | null
          is_primary?: boolean
          created_at?: Timestamptz
        }
        Relationships: []
      }
      user_roles: {
        Row: {
          user_id: string
          role: UserRoleEnum
          granted_at: Timestamptz
          revoked_at: Timestamptz | null
        }
        Insert: {
          user_id: string
          role: UserRoleEnum
          granted_at?: Timestamptz
          revoked_at?: Timestamptz | null
        }
        Update: {
          user_id?: string
          role?: UserRoleEnum
          granted_at?: Timestamptz
          revoked_at?: Timestamptz | null
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: UserRoleEnum
    }
    CompositeTypes: Record<string, never>
  }
}
