-- 059_internal_pv_allocation_20260821.sql
--
-- The catalog PV is split into two explicit snapshots:
--   * pv_per_bottle: participant-facing commissionable PV (80% of total PV)
--   * internal_pv_per_bottle: internal marketing/management allocation (20%)
--
-- The internal allocation is not a participant commission and is never used by
-- write_commission_ledger. It is recorded only after an order is paid, through
-- record_internal_pv_allocations(), and is readable only by the founder and
-- Ruth Karimi.
--
-- Existing order_items are historical immutable snapshots. New order items
-- snapshot internal_pv separately; old rows remain at 0 and are not rewritten.

BEGIN;

-- -----------------------------------------------------------------------------
-- Catalog and order snapshots
-- -----------------------------------------------------------------------------

ALTER TABLE public.product_variants
  ADD COLUMN IF NOT EXISTS internal_pv_per_bottle INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.order_items
  ADD COLUMN IF NOT EXISTS internal_pv INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.product_variants
  DROP CONSTRAINT IF EXISTS product_variants_internal_pv_per_bottle_check;
ALTER TABLE public.product_variants
  ADD CONSTRAINT product_variants_internal_pv_per_bottle_check
  CHECK (internal_pv_per_bottle >= 0);

ALTER TABLE public.order_items
  DROP CONSTRAINT IF EXISTS order_items_internal_pv_check;
ALTER TABLE public.order_items
  ADD CONSTRAINT order_items_internal_pv_check
  CHECK (internal_pv >= 0);

-- Convert the current catalog snapshot. When the dynamic-PV helper from
-- migration 057 already exists, derive both shares from distributor price so
-- applying 057 before 059 cannot reduce the participant PV twice. Otherwise
-- convert the existing full-PV snapshot once. Both branches are idempotent.
DO $$
BEGIN
  IF to_regprocedure('public.pv_from_distributor_price_minor(bigint)') IS NOT NULL THEN
    UPDATE public.product_variants
       SET internal_pv_per_bottle = total.total_pv - ROUND(total.total_pv * 0.80)::INTEGER,
           pv_per_bottle = ROUND(total.total_pv * 0.80)::INTEGER
      FROM (
        SELECT id,
               public.pv_from_distributor_price_minor(distributor_price_minor) AS total_pv
          FROM public.product_variants
      ) AS total
     WHERE public.product_variants.id = total.id;
  ELSE
    UPDATE public.product_variants
       SET internal_pv_per_bottle = ROUND(pv_per_bottle * 0.25)::INTEGER,
           pv_per_bottle = ROUND(pv_per_bottle * 0.80)::INTEGER
     WHERE internal_pv_per_bottle = 0
       AND pv_per_bottle > 0;
  END IF;
END;
$$;

COMMENT ON COLUMN public.product_variants.pv_per_bottle IS
  'Participant-facing commissionable PV per bottle. The commission engine uses this snapshot only.';
COMMENT ON COLUMN public.product_variants.internal_pv_per_bottle IS
  'Internal marketing/management PV per bottle. Hidden from participants and ordinary admins.';
COMMENT ON COLUMN public.order_items.commission_pv IS
  'Participant-facing commissionable PV snapshot for this order line.';
COMMENT ON COLUMN public.order_items.internal_pv IS
  'Internal marketing/management PV snapshot for this order line. Not participant commission.';

-- -----------------------------------------------------------------------------
-- Internal allocation ledger
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.internal_pv_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE RESTRICT,
  source_order_item_id BIGINT NOT NULL REFERENCES public.order_items(id) ON DELETE RESTRICT,
  variant_id BIGINT NULL REFERENCES public.product_variants(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  internal_pv INTEGER NOT NULL CHECK (internal_pv > 0),
  allocation_type TEXT NOT NULL DEFAULT 'marketing_management'
    CHECK (allocation_type = 'marketing_management'),
  allocated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (source_order_item_id, allocation_type)
);

CREATE INDEX IF NOT EXISTS internal_pv_allocations_order_idx
  ON public.internal_pv_allocations (source_order_id, allocated_at DESC);
CREATE INDEX IF NOT EXISTS internal_pv_allocations_variant_idx
  ON public.internal_pv_allocations (variant_id, allocated_at DESC);

COMMENT ON TABLE public.internal_pv_allocations IS
  'Paid-order internal marketing/management PV allocations. Restricted to the founder and Ruth Karimi.';

-- -----------------------------------------------------------------------------
-- Internal viewer authorization and RLS
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_internal_pv_viewer()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT auth.uid() IN (
    '41c9d33c-42d1-4c7a-88d0-a275cc517853'::uuid,
    'dedfac7a-fb6f-457d-9ed7-7712c6e1f93e'::uuid
  )
  AND EXISTS (
    SELECT 1
      FROM public.user_roles ur
     WHERE ur.user_id = auth.uid()
       AND ur.role = 'superadmin'::public.user_role
       AND ur.revoked_at IS NULL
  );
$$;

REVOKE ALL ON FUNCTION public.is_internal_pv_viewer() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_internal_pv_viewer() TO authenticated;

ALTER TABLE public.internal_pv_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_pv_allocations FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS internal_pv_allocations_internal_read
  ON public.internal_pv_allocations;
CREATE POLICY internal_pv_allocations_internal_read
  ON public.internal_pv_allocations
  FOR SELECT
  TO authenticated
  USING (public.is_internal_pv_viewer());

REVOKE ALL ON TABLE public.internal_pv_allocations FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.internal_pv_allocations TO authenticated;
GRANT ALL ON TABLE public.internal_pv_allocations TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.internal_pv_allocations_id_seq TO service_role;

-- Column-level grants prevent the internal catalog and order snapshots from
-- being returned by direct anon/authenticated select=* requests. Existing
-- application queries are changed to explicit public projections in the code.
REVOKE SELECT ON public.product_variants FROM PUBLIC, anon, authenticated;
GRANT SELECT (
  id, product_id, sku, size_ml, retail_price_minor, distributor_price_minor,
  selling_price_minor, pv_per_bottle, weight_g, inventory_qty, is_active,
  created_at
) ON public.product_variants TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_variants TO service_role;

REVOKE SELECT ON public.order_items FROM PUBLIC, anon, authenticated;
GRANT SELECT (
  id, order_id, variant_id, bundle_id, quantity, unit_price_minor,
  line_total_minor, is_commissionable, commissionable_amount_minor,
  commission_pv
) ON public.order_items TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.order_items TO service_role;

-- -----------------------------------------------------------------------------
-- Idempotent paid-order recorder
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.record_internal_pv_allocations(p_order_id BIGINT)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_status public.order_status;
  v_count INTEGER := 0;
BEGIN
  SELECT status
    INTO v_status
    FROM public.orders
   WHERE id = p_order_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'order % not found', p_order_id USING ERRCODE = 'no_data_found';
  END IF;

  IF v_status <> 'paid' THEN
    RAISE EXCEPTION 'order % is not paid (status=%)', p_order_id, v_status
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  INSERT INTO public.internal_pv_allocations (
    source_order_id,
    source_order_item_id,
    variant_id,
    quantity,
    internal_pv,
    allocation_type,
    allocated_at
  )
  SELECT
    oi.order_id,
    oi.id,
    oi.variant_id,
    oi.quantity,
    oi.internal_pv,
    'marketing_management',
    COALESCE(o.paid_at, NOW())
    FROM public.order_items oi
    JOIN public.orders o ON o.id = oi.order_id
   WHERE oi.order_id = p_order_id
     AND oi.internal_pv > 0
  ON CONFLICT (source_order_item_id, allocation_type) DO NOTHING;

  GET DIAGNOSTICS v_count = ROW_COUNT;

  INSERT INTO public.audit_log (
    actor_id, action, resource_type, resource_id, after_data
  ) VALUES (
    NULL,
    'internal_pv.allocations_written',
    'orders',
    p_order_id::TEXT,
    jsonb_build_object(
      'rows_written', v_count,
      'internal_pv', COALESCE((
        SELECT SUM(internal_pv)
          FROM public.order_items
         WHERE order_id = p_order_id
           AND internal_pv > 0
      ), 0)
    )
  );

  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.record_internal_pv_allocations(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_internal_pv_allocations(BIGINT) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_internal_pv_allocations(BIGINT) TO service_role;

NOTIFY pgrst, 'reload schema';

COMMIT;
